---
- name: Acte-I
  hosts: linux
  gather_facts: false

  tasks:
    - name: Copie du fichier data.txt
      ansible.builtin.copy:
        src: data.txt
        dest: /tmp
        mode: "0600"
      tags: never

    - name: Remplacement de la ligne "Ouf, c'est fini !" par "Bientôt la pause"
      ansible.builtin.lineinfile:
        regex: ^Ouf, c'est fini !$
        line: Bientôt la pause
        dest: /tmp/data.txt
        backup: true
