---
- name: Acte-I
  hosts: linux
  gather_facts: false

  tasks:
    - name: Copie du fichier data.txt
      ansible.builtin.copy:
        src: data.txt
        dest: /tmp
        mode: "0600"

    - name: S'assurer de la présence de la ligne "Ouf, fini !"
      ansible.builtin.lineinfile:
        line: Ouf, c'est fini !
        dest: /tmp/data.txt
        backup: true
