---
- name: Installation d'un serveur Redis
  hosts: linux
  gather_facts: false
  become: true

  vars:
    redis_enabled: false
    redis_state: stopped

  tasks:
    - name: Installation du paquet redis-server
      ansible.builtin.package:
        name: "{{ redis_package_name }}"
        state: present
        update_cache: true

    - name: Paramètrage du service redis
      ansible.builtin.systemd:
        name: "{{ redis_service_name }}"
        state: "{{ redis_state }}"
        enabled: "{{ redis_enabled }}"
